# we will use openjdk 8 with alpine as it is a very small linux distro
FROM openjdk:8-jre-alpine3.9

# Add dependencies
RUN apk add curl

# Set WORKDIR
WORKDIR /app

# Expose PORT 8080
EXPOSE 8080

# copy the packaged jar file into our docker image
COPY airports-assembly-1.0.1.jar /app/airports-assembly-1.0.1.jar 

# set the startup command to execute the jar
CMD ["java", "-jar", "/app/airports-assembly-1.0.1.jar"]

