name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: docker login
       env:
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
       run: |
         docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
     
     - name: Build the airports Docker image
       run: docker build . --file dockerfile.airports --tag barbhua786/airports-assembly:1.0.1
     - name: Build the countries Docker image
       run: docker build . --file dockerfile.countries --tag barbhua786/countries-assembly:1.0.1
     - name: Build the nginx Docker image
       run: docker build . --file dockerfile.nginx --tag barbhua786/nginx:1.0.1

     - name: Docker Push for countries
       run: docker push barbhua786/airports-assembly:1.0.1
     - name: Docker Push for countries
       run: docker push barbhua786/countries-assembly:1.0.1
     - name: Docker Push for nginx
       run: docker push barbhua786/nginx:1.0.1
